spring:
  application:
    name: resume-api
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8080
  cloud:
    config:
      fail-fast: true
server:
  port: 8081